

CONFIG_TOOLCHAIN_PATH="/usr/bin"
CONFIG_TOOLCHAIN_PREFIX="arm-none-eabi-"
#CONFIG_TOOLCHAIN_PREFIX="arm-linux-gnueabihf-"
CONFIG_LIB_STM32HAL_ENABLE=y
CONFIG_LIB_FREERTOS_ENABLE=y
CONFIG_FREERTOS_CMSIS_RTOS_V2=y
CONFIG_SDK_LOG_LEVEL=5
